version: '2'
services:
  quartz:
    container_name: quartz
    build: .
    depends_on:
     - mysql
     - postgres
     - firebird
     - oracle
    entrypoint: ./build.sh TestLinux

  mysql:
    container_name: mysql
    build: docker/mysql
    ports:
     - "3306:3306"
  
  postgres:
    container_name: postgres
    build: docker/postgres
    ports:
     - "5432:5432"

  firebird:
    container_name: firebird
    build: docker/firebird
    ports:
     - "3050:3050"

  oracle:
    container_name: oracle
    build: docker/oracle
    ports:
     - "1521:1521"
    environment:
     - ORACLE_ALLOW_REMOTE:true

  sqlserver:
    container_name: sqlserver
    build: docker/sqlserver
    ports:
     - "1433:1433"

